### ISSUE TITLE
GUI: Can't pull up search results (401 error)

### ISSUE THREAD

**Issue by procopes** [peeringdb/1to2#1]
OS: Mac OS X
Browser: Firefox (v35.0.1)
When you click on a search result, you get directed to https://beta.peeringdb.com/network/5 and see the attached 401 error message :
![screen shot 2015-01-29 at 2 32 04 pm](https://cloud.githubusercontent.com/assets/10765467/5969080/f5536180-a7d3-11e4-8f8b-51bf8f2fc9ad.png)
I was not able to get any search results to pull up successfully.

**Comment by fhibler** [comment]
Hi,
I think this is fixed by now.

https://beta.peeringdb.com/net/5

**Comment by grizz** [comment]
Agreed
