### ISSUE TITLE
Check extra space and alphabetical sort "Role" dropdown

### ISSUE THREAD

**Issue by ghankins** [peeringdb/1to2#101]
I'm pretty sure there's a leading space in front of "Technical" in the menu.  Or maybe it's just the font but it looks strange on Firefox under Linux and Windows.

Alphabetical sort the menu please:
Abuse
NOC
Policy
Public Relations
Sales
Technical

Also alphabetical sort the Role display box if it isn't already.

**Comment by ghankins** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8171907/14582318/6bb336a4-03cf-11e6-997f-32d459fcd705.png)

**Comment by vegu** [comment]
alphabetical order fixed in a3d873 (v2.0.10) - no extra space infront of technical, appears to be some ff rendering issue
