### ISSUE TITLE
Network counts are wrong

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/1to2#105]
Viewing https://www.peeringdb.com/fac/86 reveals inaccurate network counts:

<img width="561" alt="screen shot 2016-04-21 at 8 31 02 pm" src="https://cloud.githubusercontent.com/assets/1417833/14730904/0273b634-0800-11e6-935c-02189fef9057.png">

The network count should 'unique' against ASN, so that multiple routers and IPv4/IPv6 addresses are not overcounted.

For example, https://www.peeringdb.com/ix/1285 SIX Seattle (Jumbo)'s present count of 4 should really be 1, since at present it is just Altopia.:

<img width="1165" alt="screen shot 2016-04-21 at 8 33 24 pm" src="https://cloud.githubusercontent.com/assets/1417833/14730935/53e106ca-0800-11e6-91cb-bbbc8b58d17e.png">

**Comment by vegu** [comment]
fixed 6214863 (2.0.10)
