### ISSUE TITLE
Search: Does not work with ASNs

### ISSUE THREAD

**Issue by huggi** [peeringdb/1to2#11]
I just realized that for e.g. 'Epsilon' https://www.peeringdb.com/private/participant_view.php?id=6852 they are using AS44356 as their primary ASN and use: AS23936 as their Also Known field.

- When I search for 'Epsilon' I will find them, but if I use AS44356 or AS23936 I will not find them. 
- When I search for 'AS13030' I also don't get anything
- When I use 13030 it shows me the right entry of: https://beta.peeringdb.com/net/163

Is there any chance to make this happen in the new search? I know the value in your db is 13030 but I'm used to type asXYZ.

**Comment by grizz** [comment]
fixed 2bb14d0 also added search for any ref tag
