### ISSUE TITLE
Record / retrieve ARP sponge MAC address for IXPs

### ISSUE THREAD

**Issue by job** [peeringdb/1to2#12]
It would be useful if the ARP Sponge's MAC address can be retrieved from PeeringDB.

Unsure if there already is a good datasource (like Euro-IX DB) for this? If not PeeringDB should have a field where IXPs can fill this in or Euro-IX DB should be extended to record that.

**Comment by grizz** [comment]
I'm not sure of a good data source for that, but feel free to add a field to the IXP model :)

**Comment by job** [comment]
I think euro-ix should be owner of the data
