### ISSUE TITLE
IXP Data wrong

### ISSUE THREAD

**Issue by lochiiconnectivity** [peeringdb/1to2#13]
for network 116 (as8426), PDB2 GUI and API shows we are on ix 1 (LINX Extreme) twice, whereas in fact we are on both Extreme and Juniper. PDB1 does not have this problem. PDB2 only has an IX entry for Extreme, not Juniper, were they accidentally merged?

**Comment by grizz** [comment]
this is a data integrity issue with the ixf merge, fix may have to wait until ixf db is finalized / launched

**Comment by grizz** [comment]
Largely improved, still need to sort out a few things with ixfdb.

**Comment by neufeind** [comment]
Could it be this is fixed meanwhile? Two separate LANs show up meanwhile. https://beta.peeringdb.com/net/116

**Comment by grizz** [comment]
That was part of the improvement, there's still a few that need to have the sync fixed tho.

**Comment by grizz** [comment]
I believe this is all fixed now, let us know if anyone sees other issues.
