### ISSUE TITLE
New details: for IXP, ISP or datacenter facilities

### ISSUE THREAD

**Issue by huggi** [peeringdb/1to2#15]
Hi guys

I just came across the WP-article [1] of PeeringDB and saw that "consists of user contributed data" and was thinking about letting all participants of PeeringDB let add their back-link to Wikipedia.
I'll guess for e.g. if XYZ links back to WP that is also positive for PeeringDBs PageRank at Google :)

Thanks!

Marco 

[1] https://en.wikipedia.org/wiki/PeeringDB

**Comment by grizz** [comment]
I'm not really sure what you're asking, could you clarify?

**Comment by huggi** [comment]
Sure, I mean the ability to add a link to their IXP, ISP or datacenter to a Wikipedia Article, let me give you and example for LINX, they would add: https://en.wikipedia.org/wiki/London_Internet_Exchange

**Comment by grizz** [comment]
They can already do that in the notes if they want to, I personally don't see any value in adding a field for that specifically at this time, although that may change in the future.
