### ISSUE TITLE
GUI: Screen refresh "resets" cursor location and causes typos

### ISSUE THREAD

**Issue by procopes** [peeringdb/1to2#2]
OS: Mac OS X
Browser: Firefox v35.0.1

When typing in a search term the screen refreshes from the "center" text box to the "upper right" text box. When it refreshes the screen, the cursor resets the location. The result that if a user is typing, it introduces a typo and makes the search results useless.

**Comment by vegu** [comment]
fixed in 1.9.6
commit f86c22da4f140057563ba7fdd74a671b2562b5ad
