### ISSUE TITLE
API field names inconsistencies

### ISSUE THREAD

**Issue by paravoid** [peeringdb/1to2#20]
An "asn" query returns "network" and "ix_lan" fields under the "ixlink_set", but these need to be queried by hitting the "net" and "ixlan" endpoints. I'm not sure if there are more cases like those yet.

**Comment by grizz** [comment]
Please let us know with any other ones you find.

**Comment by huggi** [comment]
IXP Search:
Search with longname in the exchange name field does not result anything, sample: Cameroon =0 for e.g. for CAMIX =1.

**Comment by grizz** [comment]
mostly fixed with e9bf4f9 294a543
Still need to decide if we want to change net to network

**Comment by grizz** [comment]
updated all field names to short names
