### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by paravoid** [peeringdb/1to2#22]
I would highly recommend versioning the API (e.g. /api/v1) — no matter how good of a job you & the community will do to vet the current API now, there's always going to be a need to evolve it after the fact and it'd be nice to do so without breaking everyone's assumptions/code.

**Comment by grizz** [comment]
Yep, was already planned, thanks.

**Comment by grizz** [comment]
Decided we'll leave it as is, if we need to goto a different API later, we can use /api2/, etc.
