### ISSUE TITLE
ASN Redirects 

### ISSUE THREAD

**Issue by huggi** [peeringdb/1to2#23]
Will the current redirects:
http:// and/or https://<asn>.peeringdb.com to http://www.peeringdb.com/view.php?asn=3320 resp. https://beta.peeringdb.com/net/196 work in the near future?

I think google likes it anyway:
https://www.google.com.sg/?gfe_rd=cr&ei=l7IwVaP1G5DW8gfojoCoBg&gws_rd=ssl#q=as3320.peeringdb.com

**Comment by grizz** [comment]
They will work when it's rolled out, yes.

http://as3320.b.peeringdb.com already is setup for testing the as redirect for example.
