### ISSUE TITLE
API exposes internal database ids

### ISSUE THREAD

**Issue by htj** [peeringdb/1to2#26]
Hi

The new http/json api exposes internal database id (AFAICT), which is considered bad practice, as it exposes internal structure, and makes any future internal changes, such as schema changes very tricky.

So, this is good:
curl -X GET https://beta.peeringdb.com/api/asn/2603

Bad:
curl -X GET https://beta.peeringdb.com/api/net/1721

Similarly, database ids are exposed in a lot of the exposed data:
        {
          "network": 1721, 
          "facility": 536, 
          "local_asn": 2603
        }

        {
          "network": 1721, 
          "ix_lan": 27, 
          "notes": "", 
          "speed": 10000, 
          "asn": 2603, 
          "ipaddr4": "193.239.116.53", 
          "ipaddr6": "2001:7f8:13::a500:2603:1"
        }, 

Generally internal database ids, should only be used in joins, etc. and should never leave the application. Only "business" data should be exposed to the client.

I realize this may complicate some things.

Thanks for making peeringdb. It has been a huge help in automating parts of our peering setup at NORDUnet.

**Comment by grizz** [comment]
They're not database ID specifically, they're reference handles.. We use them to synchronize data between autonomous databases, they're guaranteed static, and thus will remain exposed.
