### ISSUE TITLE
Private Peering Facilities - Consider dropping the L2 types?

### ISSUE THREAD

**Issue by laptop006** [peeringdb/1to2#29]
ex: https://beta.peeringdb.com/net/433
ie "SONET ETHER ATM"

I remember in the past checking, and no live facilities had anything but ethernet.

**Comment by grizz** [comment]
I tend to agree on dropping it, but there are plenty of live facilities that have sonet / atm checked. Maybe bring it up on the mailing list?

**Comment by job** [comment]
The L2 types are irrelevant when querying for facilities. All (potential) peers want to know is whether a someone is present or not, and then they'll privately negotate what type of connectivity etc. The facilities are not used in an automated fashion to set up peering.

Of course we can bring it up on the list!

**Comment by grizz** [comment]
http://lists.peeringdb.com/pipermail/pdb-tech/2015-September/000057.html

Discussed and dropped.
