### ISSUE TITLE
GUI: IPv4/IPv6 participant IPs mixed up

### ISSUE THREAD

**Issue by fhibler** [peeringdb/1to2#3]
![screen shot 2015-02-08 at 10 51 33 am](https://cloud.githubusercontent.com/assets/1452221/6096426/c4da05fc-af87-11e4-96f8-51d4cb7c77a0.png)

I was checking out v2 and saw, that on the IXP display pages (f.e.
https://beta.peeringdb.com/ix/341?s=20), you are mixing up IPv4 and
IPv6 fields. Is this only a label error or are you importing them
wrongly in the DB?

**Comment by vegu** [comment]
fixed in 1.9.5
commit 4b28d50c5033b037ec8c8626ef47f91902a8a353
