### ISSUE TITLE
Database is not accurate

### ISSUE THREAD

**Issue by zivno** [peeringdb/1to2#34]
Hello Peeringdb,

For AS8551
The details on the 2.0 version is not updated with the old peeringdb website.

Thanks.

**Comment by job** [comment]
Which details are you specifically referring to?

**Comment by zivno** [comment]
Hi Job,

These are:

Approx Prefixes Announced<javascript:void(0);> – wrong number
Protocols Supported – not mentioned
Peering Contacts – wrong contacts

Thanks,
  [cid:image001.jpg@01D0A378.10004300]

Ziv

Noah



Network Engineer


Network Engineering

Planning Division

Information Technology Dep.





[cid:image002.jpg@01D0A378.10004300]

+972-765014505

[cid:image003.jpg@01D0A378.10004300]

+972-504014505

[cid:image004.jpg@01D0A378.10004300]

+972-153765014505

[cid:image005.jpg@01D0A378.10004300]

zivn@bezeqint.co.il<mailto:zivn@bezeqint.co.il>



[cid:image006.jpg@01D0A378.10004300]

[cid:image007.jpg@01D0A378.10004300]<http://twitter.com/BezeqBenleumi>

[cid:image008.jpg@01D0A378.10004300]<http://www.facebook.com/home.php?#/BezeqBenleumi>



[cid:image009.jpg@01D0A378.10004300]<http://www.bezeqint.net/>

**Comment by grizz** [comment]
fixed 87758d4 44799d4
