### ISSUE TITLE
DB: Local facilities to IXPs

### ISSUE THREAD

**Issue by fhibler** [peeringdb/1to2#4]
The issue seems to rely on the import modul from v1 to v2. The match for facilities in incorrect and therefore showing wrong sites associated with the IXP.

Examples:
Correct: https://www.peeringdb.com/private/exchange_view.php?id=31
Wrong: https://beta.peeringdb.com/ix/9

**Comment by grizz** [comment]
import bug from the ixf/pdb id merger

**Comment by grizz** [comment]
Fixed in dev
