### ISSUE TITLE
Discrepancy between v1 and v2 for ASN 29676

### ISSUE THREAD

**Issue by peterpaulhernandez** [peeringdb/1to2#41]
I am seeing the following:

https://beta.peeringdb.com/net/2582
LONAP	29676	5.57.80.202	None	1G

vs
http://www.peeringdb.com/view.php?asn=29676
LINX Extreme LAN 	29676 	195.66.238.139 	1000 
LINX Extreme LAN 	29676 	2001:7f8:4:1::73ec:1 	1000 
LINX Juniper LAN 	29676 	195.66.226.139 	1000 
LINX Juniper LAN 	29676 	2001:7f8:4::73ec:1 	1000 
LONAP 	29676 	2001:7f8:17::73ec:1 	1000 
LONAP 	29676 	5.57.80.202 	1000 

It looks like some of the entries are missing in the new version.

**Comment by grizz** [comment]
Sync was disabled, sorry!
