### ISSUE TITLE
fac_set and ixlink_set not included in raw net pull starting 1.9.15

### ISSUE THREAD

**Issue by Segsfault** [peeringdb/1to2#46]
Querying a specific id will return the fac_set and ixlink_set lists :
https://beta.peeringdb.com/api/net/8511

But pulling the whole set does not:
https://beta.peeringdb.com/api/net/

This may be by design but it did return the lists prior to 1.9.15.

**Comment by vegu** [comment]
Starting 1.9.15 all list GET results are shallow by default, you may pass the "depth" parameter in the URL in order to get sub lists as before. 

https://beta.peeringdb.com/api/net?depth
