### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by fhibler** [peeringdb/1to2#5]
Encoding does not seem to be right for some chars (UTF-8)? 

In this case, company name:
Correct: AC Systemy Komputerowe Stanisław Bor sp.j. (https://www.peeringdb.com/private/participant_view.php?id=3736)

Wrong: AC Systemy Komputerowe StanisÅ‚aw Bor sp.j.
(https://beta.peeringdb.com/net/3736)

API shows it as AC Systemy Komputerowe Stanis\u00c5\u201aaw Bor sp.j.
(https://beta.peeringdb.com/api/net/3736)

**Comment by grizz** [comment]
This is actually caused from the old data being utf8 in a latin1 database, there's a few duplicate key errors when converting that will have to be hand fixed.

**Comment by job** [comment]
This query finds all trouble entries, there are ~ 224:

```SELECT name, convert(cast(convert(`name` using latin1) as binary) using utf8), id from peerParticipants where name NOT LIKE convert(cast(convert(`name` using latin1) as binary) using utf8);```

**Comment by job** [comment]
After cutover I can fix the 224 wrong names in pdb2 which should not have encoding issues if I copy paste the names :-)

**Comment by vegu** [comment]
fixed in 1.9.20 (2828e84)
