### ISSUE TITLE
Unicode is broken in record names

### ISSUE THREAD

**Issue by ghankins** [peeringdb/1to2#58]
For example: https://beta.peeringdb.com/net/8974
Name "VM OPENLINK COMUNICAÇÃO MULTIMIDIA E INFORMÁTICA LTDA" in v1.0 is displayed as "VM OPENLINK COMUNICAÃ‡ÃƒO MULTIMIDIA E INFORMÃTICA LTDA" in v2.0.

There are probably other examples of where unicode is broken.

**Comment by grizz** [comment]
Same issue as #5

**Comment by vegu** [comment]
fixed in 1.9.20 (2828e84)
