### ISSUE TITLE
DB: Some v6 addresses wrongly imported

### ISSUE THREAD

**Issue by fhibler** [peeringdb/1to2#6]
It seems, that if a network got text in their IP field for an IXP, it gets converted to a very strange IPv6 address. Also sometimes entries appear for those "weird" IPv6 addresses, even when there is no weird entry in PDB1:

For example:
Case 1:
https://www.peeringdb.com/private/participant_view.php?id=433&peerParticipantsPublics_mPage=2
CIX 	36040 	via CIX route server 	10000 
"via CIX route server" becomes "4349:5820:726f:7574:6520:7365:7276:6572"

Case 2:
https://www.peeringdb.com/private/participant_view.php?id=433&peerParticipantsPublics_mPage=4
ECIX-HAM 	15169 	2001:7f8:8:10::3b41:0:1/64 	10000
this entry becomes in v2 (https://beta.peeringdb.com/ix/341)
ECIX-HAM	15169	None	2001:7f8:8:10:0:3b41:0:1	10000
ECIX-HAM	15169	None	3139:332e:3432:2e31:3535:2e34:362f:3234	10000

There are other networks affected as well (so far found https://beta.peeringdb.com/net/433, https://beta.peeringdb.com/net/670, https://beta.peeringdb.com/net/1964, https://beta.peeringdb.com/net/1728, https://beta.peeringdb.com/net/2310, etc.). Just have a look at https://beta.peeringdb.com/ix/9 to figure out more networks.

**Comment by grizz** [comment]
bad ipaddress module version, fixed in dev
