### ISSUE TITLE
Mirror issue

### ISSUE THREAD

**Issue by htj** [peeringdb/1to2#67]
https://www.peeringdb.com/private/participant_view.php?id=1721

https://beta.peeringdb.com/net/1721

CIXP addresses didn't come to be v2 for some reason.

**Comment by vegu** [comment]
Thanks for the feedback!

It is there, but it appears to be failing IPv6 validation - so it is marked during import and will need to be fixed or removed after rollover to v2

`        
{
          "id": 5362, 
          "ixlan_id": 33, 
          "notes": "2001:7F8:1C:24A::a2b::1", 
          "speed": 10000, 
          "asn": 2603, 
          "ipaddr4": null, 
          "ipaddr6": null, 
          "is_rs_peer": false, 
          "created": "2016-02-04T09:16:02Z", 
          "updated": "2016-02-04T09:16:02Z", 
          "status": "ok"
}`

**Comment by vegu** [comment]
This particular data point appears to be resolved, closing ticket

**Comment by htj** [comment]
Hi. Yeah, I got our peering guy to fix it.

However, I think it would be nice if the maintainer of the peeringdb entry was notified of these errors.
