### ISSUE TITLE
No name for peering facilities in asn/net search

### ISSUE THREAD

**Issue by htj** [peeringdb/1to2#69]
Hi

I'm trying to migrate our v1 sql usage to the v2 json api. Our system has the engineer typing in the as to peer with, and potentially a set of IXes. If blank, the system will fill out all the common ones, with description, ip addresses, as set, prefix limit, everything.

Trying out with our own as:
curl https://beta.peeringdb.com/api/asn/2603
This gives as name, prefix limits. For peering facilities, there are lists like this:

      "netfac_set": [
        {
          "id": 8383,.
          "fac_id": 1,.
          "local_asn": 2603,.
          "created": "2016-02-02T16:24:29Z",.
          "updated": "2016-02-02T16:24:29Z",.
          "status": "ok"
        },.

      "netixlan_set": [
        {
          "id": 5362,
          "ixlan_id": 33,
          "notes": "2001:7F8:1C:24A::a2b::1\t",
          "speed": 10000,
          "asn": 2603,
          "ipaddr4": null,
          "ipaddr6": null,
          "is_rs_peer": false,
          "created": "2016-02-04T09:16:02Z",
          "updated": "2016-02-04T09:16:02Z",
          "status": "ok"
        },

This gives me IP addresses, but I have no idea how to correlate facilities. Our system uses terms like AMS-IX, LINX, etc.

To get the facility names, I'd need to do a get for each ixlan. Like this:

curl --silent https://beta.peeringdb.com/api/ixlan/33

For us, that would be
grep ixlan_id 2603.json |sort|uniq|wc -l
17
entries, but many networks have a lot more.

AMS-IX ixlan entry is 750K. LINX is 640K. I'd say it is around 3-4 MB data in total split over 18 requests to get the data I need to set up peering with one network.

That is way too much.

I could do request to /api/ix/XX but then I'd have to know that those two id are the same. But it would still be way to many requests.

Please include name for facility in the asn/net search. This makes it easy for people to get the info they need in one request, and is going to save a lot of resources in your server/bandwidth setup :-) 

Maybe more stuff should be in there (long_name). This solves my case though.

For reference here is our current SQL queries:

        "SELECT peerParticipants.name, peerParticipants.irr_as_set, peerParticipants.info_prefixes " +
        "FROM peerParticipants WHERE peerParticipants.asn = ?;"

        "SELECT mgmtPublics.name, peerParticipantsPublics.local_asn, peerParticipantsPublics.local_ipaddr " +
        "FROM mgmtPublics LEFT OUTER JOIN peerParticipantsPublics ON (mgmtPublics.id = peerParticipantsPublics.public_id) " +
        "LEFT OUTER JOIN peerParticipants on (peerParticipantsPublics.participant_id = peerParticipants.id) " +
        "WHERE peerParticipants.asn = ?;"

**Comment by vegu** [comment]
You can expand objects via the depth parameter 

Sounds like https://beta.peeringdb.com/api/asn/2603?depth=3 would do what you are asking for

**Comment by htj** [comment]
Thanks for the reply.

depth=3 only expands names for the netfac_sec. To expand names for the netixlan_set, depth=4 is needed.

Have you considered having a bit better defaults here. I think a lot more would need the names, where the various id doesn't really have value to most people.

**Comment by grizz** [comment]
fixed 2.0.7
