### ISSUE TITLE
variable name consistency in asn/net facility listing

### ISSUE THREAD

**Issue by htj** [peeringdb/1to2#70]
In asn/net search, one get results like hits:

      "netfac_set": [
        {
          "id": 8383,.
          "fac_id": 1,.
          "local_asn": 2603,.
          "created": "2016-02-02T16:24:29Z",.
          "updated": "2016-02-02T16:24:29Z",.
          "status": "ok"
        },.

      "netixlan_set": [
        {
          "id": 5362,
          "ixlan_id": 33,
          "notes": "2001:7F8:1C:24A::a2b::1\t",
          "speed": 10000,
          "asn": 2603,
          "ipaddr4": null,
          "ipaddr6": null,
          "is_rs_peer": false,
          "created": "2016-02-04T09:16:02Z",
          "updated": "2016-02-04T09:16:02Z",
          "status": "ok"
        },

I think this should be local_asn for netixlan_set as well.

**Comment by grizz** [comment]
Agreed, not sure how we missed that. We will probably change local_asn to asn, when we need to make api breaking changes.
