### ISSUE TITLE
Using API requires a lot of guessing

### ISSUE THREAD

**Issue by htj** [peeringdb/1to2#72]
Hi

Looking at: https://beta.peeringdb.com/apidocs/

Having to guess the distinction between ix, ixfac, ixlan, and ixpfx is rather confusing. I'm sure it makes sense for whoever designed the schema.

Right now, I'm trying to list all the networks at a set off IXes. SQL query for reference:

SELECT DISTINCT mgmtPublics.name, peerParticipantsPublics.local_asn, peerParticipants.asn
FROM mgmtPublics
LEFT OUTER JOIN peerParticipantsPublics ON (mgmtPublics.id = peerParticipantsPublics.public_id)
LEFT OUTER JOIN peerParticipants on (peerParticipantsPublics.participant_id = peerParticipants.id)
WHERE peerParticipants.asn IN (#);

We use this to run a monthly check that if we are missing peer at a certain IX.

Naturally I'd like to this in a single request :-)

Closest I've come is:
https://beta.peeringdb.com/api/ix?depth=3
Which gives me all IXes, and net_set, but doesn't expand the networks.

Having a way to limit which IXes to lookup would be good to save bandwidth and query time.

**Comment by vegu** [comment]
Some further documentation is needed regarding the various entity types, we are doing another documentation pass soon and should hopefully flesh that out a bit.

As to your problem, you can do a combination of reverse lookup and set filtering:

So if you know which IXes you want to lookup (in this example id 1 and 2)

https://beta.peeringdb.com/api/ixlan?ix_id__in=1,2&depth=2 - to get all the ixlans and their net_sets

**Comment by htj** [comment]
Is there not a way to query by IX name?

Querying by business data should always be preferred over internal ids (which shouldn't even be exposed IMHO, but  thats another ticket).

**Comment by vegu** [comment]
https://beta.peeringdb.com/api/ix?name=xxx for exact filtering, or use any of the string filters that the api supports

You cannot query the ixlan endpoint by ix name, so in this case you would have to retrieve the ix ids first then run the request i mentioned above with the ids from the first request.

We discussed the exposed ids - please refer to #26 once more

**Comment by htj** [comment]
So
https://beta.peeringdb.com/api/ixlan?ix_id__in=1,2
Doesn't actually work. It lists way more than it should.

But this seems to work:
https://beta.peeringdb.com/api/ix?name__in=AMS-IX,LINX Juniper LAN"
However adding depth only gives my facilities, not networks.

However the name__in has rather wonky behavior. Doing:
https://beta.peeringdb.com/api/ix?name__in?AMS-IX,DE-CIX
Gives me all IXes. Which it should not.

Also, none of these queries does what we need.

**Comment by vegu** [comment]
You are correct __in filter on ix_id in ixlan appears to be broken in 1.9.20 - i've opened a separate issue for it - #73

**Comment by vegu** [comment]
Issue has been fixed and will be rolled out with 1.9.21

So going by your requirement

> Right now, I'm trying to list all the networks at a set off IXes. SQL query for reference:

once this is working this should still get you what you need

Meanwhile on 1.9.20 - ix__in is still functional - which is what i used to test, i apologize.

Testing with ix 64 and 31 (as 1 and 2 actually have empty net sets)

https://beta.peeringdb.com/api/ixlan?ix__in=64,31&depth=2

can you confirm for me that this gives you the data you require. thanks

**Comment by vegu** [comment]
Importer malfunction #74 would have caused a lot of the ixlan net_sets to be empty as well - fixed now

**Comment by vegu** [comment]
As of 1.9.21 these work accordingly again:

https://beta.peeringdb.com/api/net?ix_id__in=1,2
https://beta.peeringdb.com/api/ixlan?ix_id__in=1,2&depth=2

Either of those should give you networks at the set of IXes you specify

**Comment by htj** [comment]
Sorry I don't think this is good enough.

Forcing people do multiple roundtrips and use arbitary ids is bad. Business data should always be the key thing to retrieve and query with. The ids only exists in peeringdb, and doesn't come from the IXes. No one is interesting in using them from an integration point-of-view.

**Comment by grizz** [comment]
Added more fields. We use ids because there's over a decade of legacy application that are written to sync with peeringdb and use ids.
