### ISSUE TITLE
Query ASN API with empty netixlan_set

### ISSUE THREAD

**Issue by uihcsc** [peeringdb/1to2#74]
When accessing the URL: https://beta.peeringdb.com/api/asn/18106 , the netixlan_set returns empty, it applies to all ASNs I tried. It was good like 24 hours ago. Is there any change to affect that? I tired both pre-auth and auth myself.

Thanks for the help in advance.
-SC

**Comment by vegu** [comment]
appears to be an importer malfunction, looking into it right now

**Comment by vegu** [comment]
data fixed - still tracking down cause

**Comment by vegu** [comment]
fixed 1786ad1  - also hotfixed on beta 1.9.20
