### ISSUE TITLE
Lookup of arbitrary parameters in REST API

### ISSUE THREAD

**Issue by lysiszegerman** [peeringdb/1to2#8]
I am currently using the MySQL interface for building peering configurations, for this I'm querying the table peerParticipantsPublics for local_ipaddr with where clauses for "local_asn" and "public_id". 

This is currently not possible with the REST API - I cannot lookup the IXP id by name and especially cannot query the IP addresses in the peering LAN for an ASN. Is there some way this functionality can be extended to the REST API?

Thanks in advance,

   Marcus

**Comment by vegu** [comment]
fixed 01fe992
