### ISSUE TITLE
'edit' in network view vs 'add' for contacts.

### ISSUE THREAD

**Issue by aaronw112358** [peeringdb/1to2#80]
For contacts there is an 'add' button that is only accessible from the edit view, but choosing 'add' does not terminate the edit session.  It should be clearer when one is editing the one-per-network items (scope, looking glass URL, etc) or editing contacts.

**Comment by grizz** [comment]
We've added a few things in 2.0.8 to make it more apparent that the add is doing something while in edit mode, any other suggestions?
