### ISSUE TITLE
Not clear how to modify a contact

### ISSUE THREAD

**Issue by aaronw112358** [peeringdb/1to2#81]
If an attribute of a contact entry for a network needs to be changed it's not clear how to save those changes (public-> private, telephone # change, etc) Additionally, heading in field should have 'Visibility' or similar verbage under 'Name' as the fields to the right say 'Phone' and 'E-mail'.  Additionally, bottom two fields are in gray print instead of normal print, is there a UI reason?

**Comment by vegu** [comment]
fixed bugs in 9ff1e15 (2.0.4) - need to discuss usability

**Comment by vegu** [comment]
fixed 77a6e4b - added another instance of "Cancel" and "Save" button to the bottom of the editor, will need to see if that is sufficient, can revisit if not
