### ISSUE TITLE
API call to ASN is missing?

### ISSUE THREAD

**Issue by uihcsc** [peeringdb/1to2#86]
https://www.peeringdb.com/asn/20940 it's in place.

https://beta.peeringdb.com/api/asn/20940 got 'not Found', so does https://www.peeringdb.com/api/asn/20940

API docs does not show the ASN API is in place: https://www.peeringdb.com/apidocs/, is it removed or replace?

Thanks,
SC

**Comment by muspelheim** [comment]
@grizz Hello, i have same problem, can you provide any information?

**Comment by grizz** [comment]
Please see http://lists.peeringdb.com/pipermail/pdb-announce/2016-March/000036.html for more details.
