### ISSUE TITLE
WebUI net page IP issues

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/1to2#87]
In the WebUI:

- Net object exchange point IP addition shouldn't require both IPv4 and IPv6 addresses.  In same cases sites will only want to add one or the other.  (imported data from PDB 1.0 allowed this, and presently shows "None" when missing)

- Speeds: New additions of, for example, "20000" display as "20000", until a screen refresh is done.  Then they display as "20G".  After the add, it should display as "20G" without a refresh being needed.

- "RS Peer" is present as an option when adding, but is not editable and is not displayed.

- For IXes like the SIX which have multiple LANs (https://www.peeringdb.com/ix/13, Standard and Jumbo in the SIX case), should the web UI display the LAN name, or would that be clutter?

**Comment by grizz** [comment]
All good feedback, thanks. 1 and 3 are done, 2 and 4 will be addressed for next release.

**Comment by grizz** [comment]
Fixed 2.0.6

**Comment by ccaputo** [comment]
On a net page when I add an exchange point config, the "Exchange" field lists "SIX Seattle" twice if I type "SIX" or "Seattle".  Is that because there are two VLANs at "SIX Seattle"?  

If yes, shouldn't the VLAN name be also listed, so the correct VLAN can be chosen?

Also, the fourth item above (VLAN name) doesn't seem to have been addressed as of 2.0.7.

**Comment by vegu** [comment]
You are correct, i misread the fourth issue, and told grizz to close this pre-maturely, it will be addressed in a future release, apologies

**Comment by vegu** [comment]
2.0.8 will add LAN name to the exchange field auto-complete in order to allow differentiating between multiple LANs at the same ix

**Comment by vegu** [comment]
fixed 4ebd411

**Comment by ccaputo** [comment]
<img width="570" alt="screen shot 2016-04-15 at 10 28 15 pm" src="https://cloud.githubusercontent.com/assets/1417833/14579321/77427a78-0359-11e6-81b3-69ccdb9e2ce3.png">

Nice work, but RS Peer is showing "true" instead of a checkbox after add.

**Comment by ccaputo** [comment]
Also, on an IX listing such as https://www.peeringdb.com/ix/13, the VLAN name should be displayed within the "Peers at this Exchange Point" listing, otherwise it seems like everyone is in the same VLAN.

**Comment by vegu** [comment]
created separate issue #98 for add VLAN name to /ix

**Comment by vegu** [comment]
fixed f42a1bb - released with 2.0.9
