### ISSUE TITLE
Allow new org registration without ASN

### ISSUE THREAD

**Issue by ghankins** [peeringdb/1to2#95]
New facilities and exchanges may not have an ASN.

Non-existent org without ASN will fail, we can make it work similarly to non existent ASN though.

**Comment by ghankins** [comment]
Update the help text too, to be clearer.

Current text:
To affiliate with a different Organization, please enter a valid ASN or Organization name below.

New box title: Affiliate with organization
(lowercase organization for consistency)

New text: 
To affiliate with an existing organization, please enter the ASN or organization name below.

To register a new network organization, please enter the ASN and organization name below.

To register a new facility or exchange organization, please enter the organization name below (ASN is optional).

**Comment by ghankins** [comment]
Change: "Existing Affiliations" to "Existing affiliations" for capitalization consistency.

Add a period to "Your affiliation with Nokia IP Labs has been approved" for punctuation consistency.

**Comment by ghankins** [comment]
To register a new facility or exchange organization, please enter the organization name below (ASN is optional).

**Comment by vegu** [comment]
fixed 335ae84
